### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by WOnder93**
Travis CI is dead, long live GitHub Actions!

### CODE REVIEW

**Comment by WOnder93** [comment]
Not sure why the run didn't start... perhaps it won't run on the first pull request only. It did run successfully after push in my fork:
https://github.com/WOnder93/selinux-policy/actions/runs/384085009

**Comment by WOnder93** [comment]
I found out there is a simpler (and much faster!) way of running stuff in a container in GH actions - PR updated.

**Comment by WOnder93** [comment]
In [udica](https://github.com/containers/udica/actions) the checks started running right after the merge, so I guess it's just a protection from running the CI until approved (merged) by the maintainer.

**Comment by zpytela** [comment]
Merged, thanks.

**Pull request merged**
