### PR TITLE
Build also the container module in CI

### PR DESCRIPTION
**Pull request by WOnder93**
...to make sure that container-selinux will still build after the
change.

### CODE REVIEW

**Comment by zpytela** [comment]
Is not `make container.pp` enough once the policy has been built?

**Comment by WOnder93** [comment]
You mean without the `-j $(nproc)`?

**Comment by zpytela** [comment]
No, `-j` is probably useless, but what I meant was
```
       - run: make container.pp -j $(nproc)
```

**Comment by WOnder93** [comment]
Ah, yes, sorry, I missed the extra `policy` target there :) Yes, I'll amend the commit.

**Comment by zpytela** [comment]
Arguments reordering also helped readability, merging, thanks.

**Pull request merged**
