### PR TITLE
RFC: Drop config.tgz from Fedora dist-git and patch conf files directly in this repo

### PR DESCRIPTION
**Pull request by bachradsusi**
For a long time, there's config.tgz in Fedora dist-git which is updated from time to time. But since it's a binary file, there's no diff's. Some conf files were not updated in config.tgz since the beginning.

I believe that all changes can be shipped directly in this directory.

This PR tries to sync conf files with this repo and refpolicy so that we could drop config.tgz.

### CODE REVIEW

**Comment by wrabcak** [comment]
Hi Petr, 

Thank you for help on this issue.

I tried to build the selinux-policy package, however one file is missing needed in Fedora distribution selinux policy, it's : 
appconfig-mcs/snapperd_contexts
appconfig-mls/snapperd_contexts
appconfig-standard/snapperd_contexts

snapperd_contexts should contain one line:
snapperd_data = system_u:object_r:snapperd_data_t:s0

Thanks,
Lukas.

**Comment by bachradsusi** [comment]
Added https://github.com/fedora-selinux/selinux-policy/pull/215/commits/b1288998b34952c472785dca420fb987d99454e5

**Comment by wrabcak** [comment]
Hi, 

selinux-policy build with this change:
https://copr.fedorainfracloud.org/coprs/lvrabec/selinux-policy-no-config-tgz/build/767990/

I'll do some testing mainly confided users should work.

**Comment by wrabcak** [comment]
I tested scratch builds with the latest Fedora Rawhide compose. No errors so far. Merging. 
Thanks Petr!

**Pull request merged**
