### PR TITLE
Add systemd-resolved manage its private runtime symlinks

### PR DESCRIPTION
**Pull request by zpytela**
Resolves: rhbz#1896796

### CODE REVIEW

**Comment by WOnder93** [comment]
s/Add/Allow/, otherwse LGTM.

**Comment by zpytela** [comment]
Changed to Allow and an interface updated, the access was requested by sssd and may be more common.

**Review by WOnder93 — APPROVED** [review]
Makes sense :+1:

**Comment by zpytela** [comment]
Thanks @WOnder93 .

**Pull request merged**
