### PR TITLE
Container

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by pmorie** [comment]
@rhatdan Any reason you chose `container_image_t` over `container_file_t` ?

**Comment by rhatdan** [comment]
Nope, although we usually refer to this as an image.  I could easily be swayed to use container_file_t.

**Comment by pmorie** [comment]
My rationale behind `container_file_t` is that in my context, we will be relabeling non-image content into this context for use by containers, and `file` seems more generally applicable than `image`.

**Comment by wrabcak** [comment]
Looks fine, I merge it and try to build new selinux-policy build

**Comment by rhatdan** [comment]
Ok @wrabcak I will open a new pull request to change container_image_t to container_file_t.

**Pull request merged**
