### PR TITLE
Add interfaces for watching and reading ifconfig_var_run_t

### PR DESCRIPTION
**Pull request by vmojzis**
Required by frr.
https://gitlab.com/redhat/centos-stream/rpms/frr/-/merge_requests/24

### CODE REVIEW

**Comment by vmojzis** [comment]
Rebased.

**Comment by vmojzis** [comment]
Changed interface names -- needs to be done in frr as well after this is merged.

**Comment by martinpitt** [comment]
Sorry, not your fault. We reported that lvm failure to https://bugzilla.redhat.com/show_bug.cgi?id=2256433 and will disable the test in rawhide, as it causes an unsalvageable mess. Please ignore.

**Comment by zpytela** [comment]
Merging, thank you.

**Pull request merged**
