### PR TITLE
Add new policy for "targetd" daemon. #1241415

### PR DESCRIPTION
**Pull request by vmojzis**

### CODE REVIEW

**Comment by mgrepl** [comment]
Looks good. Not sure why does it manage lvm locks?

**Comment by vmojzis** [comment]
Because targetd is a storage manager (https://github.com/agrover/targetd/) and it needs to be able to manage volumes in LVM volume group.

**Comment by mgrepl** [comment]
So there are library calls which directly manage LVM? Or is it done using a lvm binary?

**Comment by vmojzis** [comment]
Targetd manages logical volumes (without the use of lvm binary) and therefore needs access to files in /run/lock/lvm/.

**Comment by mgrepl** [comment]
Ok. udev and lvm policies should be called with optional_policy block and also

 +/usr/lib/systemd/system/targetd.service	

should be fixed to 

  +/usr/lib/systemd/system/targetd\.service	

at least.

**Comment by wrabcak** [comment]
or you can use: /usr/lib/systemd/system/targetd.*

**Comment by wrabcak** [comment]
What is state of this issue? @mgrepl  Could you merge it? Then I make changes in our dist-git to make it working.
Thank you.

**Pull request merged**
