### PR TITLE
Label /dev/wmi/dell-smbios as acpi_device_t

### PR DESCRIPTION
**Pull request by zpytela**
Resolves: rhbz#1899352

### CODE REVIEW

**Comment by WOnder93** [comment]
Hm... maybe we should have a different type for this one? From the info I could find, APM BIOS and Dell SMBIOS don't seem to be quite the same thing.

**Comment by zpytela** [comment]
GIven that APM is dead, would it make a difference to call it acpi? It is just a string.

**Comment by WOnder93** [comment]
If it's dead, then it's IMO all the more reason to use a separate label. If we later allow some domains access to `apm_bios_t` based on the need to use `/dev/wmi/dell-smbios` and at some point later decide to remove all APM-related stuff, how do we tell apart which rules are needed for `/dev/wmi/dell-smbios` vs. `/dev/apm_bios`? (`/dev/snapshot` should also be something else, but that's another thing...)

Or from another POV, it's easier to later merge related labels than to split an overloaded one.

**Review by WOnder93 — APPROVED** [review]
Would be nice to also update PR title for posterity, but the content looks good to me.

**Pull request merged**
