### PR TITLE
Add sssd_secrets labeling

### PR DESCRIPTION
**Pull request by rhatdan**
Also add named_filetrans interface to make sure all labels are correct.

### CODE REVIEW

**Comment by rhatdan** [comment]
@wrabcak PTAL

**Comment by lslebodn** [comment]
Would it be possible to backport this patch also to f24+ (including ded6d59f1a3a99cb080c186df74bd67601c9d835 ?
sssd-secrets is there as well.

BTW I tested latest rawhide branch and it works as expected.

**Comment by lslebodn** [comment]
And if you have  a time could you explain a purpose of `sssd_filetrans_named_content`?
I would like to get more familiar with writing SELinux policy (and sssd is the best starting point for me)

**Comment by rhatdan** [comment]
@lslebodn These interfaces are things we add for administrators.  Named filetrans allow us to specify if the admin (unconfined_t, sysadm_t) creates some content with a certain name, then it will get labeled correctly.

**Pull request merged**
