### PR TITLE
Allow iptables to read container runtime files

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
This is also needed for F26.

**Comment by vinzent** [comment]
What business has iptables with pid files of containers?

**Comment by rhatdan** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1461817

**Comment by rhatdan** [comment]
@vinzent you are right it is reading state not pid files. I have recreated the pull.  Thanks for catching this.

**Comment by vinzent** [comment]
thanks  @rhatdan  - now it's clear to me what thte change is expected to solve. docker runs iptables, iptables needs access to conainer state files.

What about including a BZ reference in the commit message? :-)

**Comment by rhatdan** [comment]
Done.

**Pull request merged**
