### PR TITLE
Add file transition for /dev/nvidia-uvm BZ(1770588)

### PR DESCRIPTION
**Pull request by zpytela**

### CODE REVIEW

**Comment by zpytela** [comment]
Reported on F31.

**Comment by wrabcak** [comment]
@zpytela , 
The fix is not complete, there is no record in devices.fc to assign right context to the path. The same issue is with all nvidia devices.

**Comment by zpytela** [comment]
devices.fc already contains:
```
/dev/nvidia.*           -c      gen_context(system_u:object_r:xserver_misc_device_t,s0)
```

**Comment by wrabcak** [comment]
Cool, you're right. 

Thanks.

**Pull request merged**
