### PR TITLE
Do not audit staff_t and user_t attempts to manage boot_t entries

### PR DESCRIPTION
**Pull request by zpytela**

### CODE REVIEW

**Comment by wrabcak** [comment]
@zpytela, 
What about other user domains?

**Comment by zpytela** [comment]
staff_u has it allowed, guest_u is not allowed to execute systemctl.

**Comment by wrabcak** [comment]
@zpytela I don't understand, you said staff_u have it allowed but you're don't auditing it in the PR.?

**Comment by zpytela** [comment]
I meant sysadm_u, sorry for the typo.

**Comment by wrabcak** [comment]
Okay good, now it make sense.

**Pull request merged**
