### PR TITLE
Allow ntp to bind and connect to ntske port.

### PR DESCRIPTION
**Pull request by jhamlin96**
See: https://bugzilla.redhat.com/show_bug.cgi?id=2246805

https://issues.redhat.com/browse/RHEL-15085

### CODE REVIEW

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/19547 landed, so please either retry the rawhide:revdeps test or force-push this PR, or ignore the failure. Sorry for the noise!

**Comment by zpytela** [comment]
@jhamlin96 Please add a note to the commit message, e. g. when this denial appears.

**Comment by jhamlin96** [comment]
@zpytela Updated, thanks

**Comment by zpytela** [comment]
@jhamlin96 thank you, can you add one more thing: how to trigger it? some configuration change is needed

**Comment by jhamlin96** [comment]
@zpytela testing PR exists and is awaiting review here: https://src.fedoraproject.org/tests/selinux/pull-request/445

Do you want the test steps listed in the commit message or PR description?

**Comment by zpytela** [comment]
@jhamlin96 To the commit message please.  The point is having the justification together with the changes so that it is more clear why the changes were made.

**Comment by jhamlin96** [comment]
@zpytela Updated

**Comment by zpytela** [comment]
Perfect, thank you.

**Pull request merged**
