### PR TITLE
Change arping path regexp to work around how fixfiles handles it

### PR DESCRIPTION
**Pull request by zpytela**
Resolves: rhbz#1832790

### CODE REVIEW

**Comment by WOnder93** [comment]
This not a "fix", but rather just a workaround. It is `fixfiles` that is broken. I would prefer if the commit title reflected that. Also, please add an explanation to the commit message about what exactly is wrong and why. IIMO, it should include at least this information:
1. fixfiles is run during selinux-policy update, trying to relabel only parts of the filesystem for which the label has changed,
2. due to a bug, fixfiles translates the `/s?bin/arping` regex to `/*`,
3. that leads to the whole system being relabeled, which takes a *very* long time.

(I assume it was late and you just wanted to post a solution quickly, but urgency of the problem is not a good excuse for rushing the commit message ;)

**Comment by zpytela** [comment]
@WOnder93, you are right in all points. However, that's what reviews are for ;).

**Comment by zpytela** [comment]
Note the same regexp is in f31+, so if this pr is accepted, it needs to be merged to f31, f32, and rawhide.

**Review by WOnder93 — APPROVED** [review]
Thanks, it looks great now :+1:

**Comment by wrabcak** [comment]
Backported to F31 and F32

**Comment by zpytela** [comment]
I am afraid the fixfiles engine cannot be fooled that easily :( It rather needs to be replaced by 2 lines.

**Pull request merged**
