### PR TITLE
Allow chronyd bind UDP sockets to ptp_event ports

### PR DESCRIPTION
**Pull request by 5umm3r15**
As a new feature added in chrony-4.2, chronyd supports an experimental NTP-over-PTP protocol.
It needs it for timestamping PTP event messages containing NTP messages.

Fix: #bz2118631

### CODE REVIEW

**Comment by zpytela** [comment]
Please instead of a generic allow rule label the port with ptp_event_port_t, udp protocol should suffice.

**Comment by zpytela** [comment]
IANA only describes the port as PTP event messages.
Copying information from the chrony developer:
It needs it for timestamping PTP event messages containing NTP messages.
Please use it in the commit message(s).

**Comment by 5umm3r15** [comment]
Fixed, can you please review it? @zpytela

**Comment by zpytela** [comment]
Merging, thank you.

**Pull request merged**
