### PR TITLE
Allow init work with its private ramfs files

### PR DESCRIPTION
**Pull request by zpytela**
The fs_ramfs_filetrans() interface was added.

Resolves: rhbz#2096857

### CODE REVIEW

**Comment by zpytela** [comment]
@WOnder93 I'd appreciate if you could take a look. This may look like an overkill given that so far only systemd used the ramfs files.

**Comment by WOnder93** [comment]
I'm thinking if it wouldn't be better (and actually easier) to just use the same labeling for tmpfs and ramfs. I.e. make `ramfs_t` an alias of `tmpfs_t` and replace the ramfs interfaces with the equivalent tmpfs ones. Both filesystems are very similar in principle and as the bug shows, they are apparently even interchangeable at least in some scenarios. Unifying labeling for the two would simplify things nicely without losing anything significant.

**Comment by zpytela** [comment]
I considered this approach, but why a different label exists then? So I only reused tmpfsfile attribute. There are now about 20 other references to ramfs interfaces.

The way how systemd uses it it tries to mount the file as ramfs first and then tmpfs in case of a failure. Certainly the file on the filesystem is used the same way.

**Comment by WOnder93** [comment]
Originally ramfs didn't support extended attributes, so it had to be treated differently from tmpfs. There is little security benefit to be had for labeling the two filesystems differently and now that ramfs has started to be used more intensively by systemd, it will be much simpler to merge them into a common label at the policy level. Then any tmpfs mount can be swapped for a ramfs one and it will work transparently, since the same label and policy rules will be used.

The `tmpfsfile` attribute is intended to group the various `*_tmpfs_t` types that can occur on a tmpfs mount. Adding ramfs_t to that attribute on its own won't make this systemd's assumption "ramfs is just like tmpfs so I can mount it wherever I would normally mount tmpfs" reflected in the policy. (And the fact that you had to add a new transition rule proves it.)

Since I'm the one bitching about it, I'll try to propose a PR, hopefully sometime this week...

**Comment by jdoss** [comment]
Can we get this merged in the meantime while @WOnder93 gets the other PR sorted out? Fedora 37 can't use systemd-creds with SELinux enabled and that is a bummer. :(

**Comment by zpytela** [comment]
@jdoss Do you see any actual problem? AFAIK systemd should fall back to using tmpfs if ramfs is not available.

**Comment by jdoss** [comment]
Hey @zpytela, yeah it is an actual problem still. See https://bugzilla.redhat.com/show_bug.cgi?id=2096857#c12 for more info.

systemd-251.5-607.fc37.x86_64 and selinux-policy-37.12-2.fc37.noarch on Fedora 37

```
$ sudo setenforce 0
$ sudo systemd-run -P --wait -p LoadCredential=abc:/etc/hosts systemd-creds cat abc
Running as unit: run-u5979.service
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 15ms 
CPU time consumed: 8ms
$ sudo setenforce 1
$ sudo systemd-run -P --wait -p LoadCredential=abc:/etc/hosts systemd-creds cat abc
Running as unit: run-u5995.service
Finished with result: exit-code
Main processes terminated with: code=exited/status=243
Service runtime: 4ms
CPU time consumed: 4ms
```

**Comment by jdoss** [comment]
Here is an ausearch that shows the denial when trying to use ramfs. systemd is not falling back to tmpfs.

```
$ sudo ausearch -m avc -m user_avc -m selinux_err -i -ts today
----
type=AVC msg=audit(11/22/2022 10:26:44.604:16255) : avc:  denied  { read write open } for  pid=1308009 comm=(sd-mkdcreds) path=/dev/shm/.#cred3a4868acd3fd2e1b dev="ramfs" ino=6217355 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:ramfs_t:s0 tclass=file permissive=0
```

**Comment by zpytela** [comment]
Learned today: There actually is a tmpfs fallback, but it only applies if the ramfs volume cannot be mounted.
We will resolve this issue either way in the next build.

**Comment by jdoss** [comment]
Thank you @zpytela!!

**Comment by WOnder93** [comment]
FWIW: I have now opened #1491, which implements my tmpfs+ramfs merge idea. Sorry for the delay :/

**Comment by zpytela** [comment]
@jdoss, I've just merged the other PR and it will be a prt of the next build. I am sorry for not resolving it earlier as I misunderstood the fallback concept.

**Comment by jdoss** [comment]
Thanks to both of you @zpytela @WOnder93! 🎉

**Pull request closed without merging**
