### PR TITLE
Allow setroubleshootd to set its resource limits

### PR DESCRIPTION
**Pull request by vmojzis**
Needed for https://gitlab.com/setroubleshoot/setroubleshoot/-/merge_requests/21

Signed-off-by: Vit Mojzis <vmojzis@redhat.com>

### CODE REVIEW

**Comment by zpytela** [comment]
@vmojzis can you add just one sentence about the reason?

**Comment by vmojzis** [comment]
> @vmojzis can you add just one sentence about the reason?

Sure, into the commit message or into setroubleshoot.te?

**Comment by vmojzis** [comment]
Also, please do not merge this yet, it may not be needed (we're discussing limiting setroubleshootd resources using systemd instead).

**Comment by vmojzis** [comment]
Not needed any more. The resource limits are set using a unit file instead.

**Pull request closed without merging**
