### PR TITLE
Add new policy for ipmievd (ipmitool). #1083031

### PR DESCRIPTION
**Pull request by vmojzis**

### CODE REVIEW

**Comment by mgrepl** [comment]
I added some cosmetic changes. See

714ccd1472bec84d54c8697a10180a439619914f

**Comment by wrabcak** [comment]
$ git pull
Already up-to-date.

$ git branch 
  f21-contrib
  f22-base
  f22-contrib
  master
  rawhide-base
* rawhide-contrib

$ git show 714ccd1472bec84d54c8697a10180a439619914f
fatal: bad object 714ccd1472bec84d54c8697a10180a439619914f

**Comment by wrabcak** [comment]
@vmojzis, please send me patch for modules-targeted-contrib related to this policy. 
Thanks.

**Comment by mgrepl** [comment]
I apologize. Updated.

**Pull request merged**
