### PR TITLE
Sync modules.conf with Fedora targeted modules

### PR DESCRIPTION
**Pull request by bachradsusi**
https://src.fedoraproject.org/rpms/selinux-policy/blob/1f5817de9171791d37d4596e33d2f643e7c9d5a0/f/modules-targeted.conf

### CODE REVIEW

**Comment by zpytela** [comment]
Merging, thank you.

**Comment by XhmikosR** [comment]
@bachradsusi @zpytela will this be backported to the version Fedora 40 is using?

**Comment by zpytela** [comment]
@XhmikosR Not planned, do you have any specific need for that?

**Comment by XhmikosR** [comment]
I believe this PR fixes the common issue with GRD not working with SELinux
enforcing mode, see https://bugzilla.redhat.com/show_bug.cgi?id=2271661

Would be nice if it was included in Fedora 40 too. :)

**Comment by bachradsusi** [comment]
This is just a sync of modules.conf from Fedora to github. It's not related to https://bugzilla.redhat.com/show_bug.cgi?id=2271661

https://bugzilla.redhat.com/show_bug.cgi?id=2271661#c16 is wrong. The right PR which should fix the bug is https://github.com/fedora-selinux/selinux-policy/pull/2269

**Comment by XhmikosR** [comment]
Ah, sorry, I came here due the wrong Bugzilla link to this PR.

I'll follow #2269 then, thanks for the reply!

**Pull request merged**
