### PR TITLE
Remove all the kdbus stuff

### PR DESCRIPTION
**Pull request by WOnder93**
KDBus is a dead project that never made it to the mainline kernel (see references in the first commit's log message), so let's stop carrying this utterly useless chunk of code in the policy.

### CODE REVIEW

**Comment by wrabcak** [comment]
LGTM,
@zpytela, if we merge this PR we need to remove kdbus module also in disgit.

**Comment by zpytela** [comment]
@wrabcak I can do it right away and create a new build with just this change to isolate it, I just want to go through this commits set first.

**Comment by wrabcak** [comment]
@zpytela so can I merge it?

**Comment by zpytela** [comment]
@wrabcak go ahead.

**Pull request merged**
