### PR TITLE
Allow avahi watch etc dirs

### PR DESCRIPTION
**Pull request by zpytela**

### CODE REVIEW

**Comment by WOnder93** [comment]
Not sure if it's worth it, but have you considered labeling the /etc/avahi subtree as avahi_conf_t? (If it's not, I'd suggest adding a comment that only /etc/avahi is known to be watched in case someone would want to do that in the future. So they don't need to worry about the other etc_t files.)

**Comment by zpytela** [comment]
It is not /etc/avahi, but rather /etc. This is quite common for /etc and /usr watches. Commit message updated.

**Comment by ghost** [comment]
Let me throw out an argument why you would label /etc/avahi with a private avahi_conf_t type:

There is an avahi_admin() interface in avahi.if. This interface is used for confined avahi administration. Imagine using that in its current shape (i.e. you have no access to write /etc/avahi). That makes this interface pretty pointless. On the other hand if you allow "avahi admin" access to write etc_t type files then that makes avahi_admin() pretty pointless as well.

**Comment by zpytela** [comment]
I actually misread the denial, avahi does chroot. Need to update the commit.

**Review by WOnder93 — APPROVED** [review]
LGTM, and I also verified that it fixes the AVC on my system.

**Pull request merged**
