### PR TITLE
Allow confined users run fwupdmgr

### PR DESCRIPTION
**Pull request by zpytela**
Allow confined users dbus_chat with fwupd_t domain
so that fwupdmgr command can be run

### CODE REVIEW

**Comment by zpytela** [comment]
The updated package builds, installs, the permissions are granted.
Before:
```
# rpm -q selinux-policy; sesearch -A -t fwupd_t -c dbus -p send_msg|grep -e staff_t -e sysadm_t -e user_t
selinux-policy-3.14.5-18.fc32.noarch
allow staff_t fwupd_t:dbus send_msg;
```
After:
```
# rpm -q selinux-policy; sesearch -A -t fwupd_t -c dbus -p send_msg|grep -e staff_t -e sysadm_t -e user_t
selinux-policy-3.14.5-18.200.bz1772619.fc32.noarch
allow staff_t fwupd_t:dbus send_msg;
allow sysadm_t fwupd_t:dbus send_msg;
allow user_t fwupd_t:dbus send_msg;
```
For staff_t the rule was already present. As guest_t is not allowed to log in a X session, AVC should not be triggered on login; if there is another way how to trigger it, then it's a dontaudit candidate.

Please review.

**Comment by wrabcak** [comment]
What about xguest?

**Comment by zpytela** [comment]
xguest has all except some dbus messages dontaudited with `dbus_dontaudit_chat_system_bus(xguest_t)`

**Comment by wrabcak** [comment]
Cool great. btw. we should check if we're even able to login via xguest, but that's off topic. 

Merging.

**Pull request merged**
