### PR TITLE
Allow snapper to create snapshots of /home/ subvolume/partition

### PR DESCRIPTION
**Pull request by levi-jcbs**

### CODE REVIEW

**Comment by zpytela** [comment]
@levi-jcbs the pr commit looks good, but can you gave me a usage example?

**Comment by levi-jcbs** [comment]
@zpytela 

I previously faced the problem, that creating a snapper configuration of the home partition (or subvolume) didn't work:
`snapper -c home create-config /home`

So I had to add the SELinux rule myself:
`semanage fcontext -a -t snapperd_data_t '/home/\.snapshots(/.*)?'`

It would be better, if this is the default behaviour. Snapshotting the home subvolume/partition is pretty common.

In my opinion, the best thing would be to allow snapper to create `.snapshot` directories everywhere. If you all agree with that, I would do a PR changing the snapper rule that way.

**Comment by levi-jcbs** [comment]
FYI currently snapper is only allowed to snapshot

- /
- /usr
- /var
- /etc

wich is quite arbitrarily. Users actually want to be able to take snapshots anywhere.

**Comment by zpytela** [comment]
Merging, thank you and sorry for the delay.

**Pull request merged**
