### PR TITLE
openfortivpn: add module

### PR DESCRIPTION
**Pull request by lkundrak**

### CODE REVIEW

**Comment by lkundrak** [comment]
<pre>
[lkundrak@fedora23-1 ~]$ cd src/network-manager-fortisslvpn/contrib/
[root@fedora23-1 contrib]# perl fortiserve.pl --pppd ./antipppd.pl >/dev/null 2>&1 &
[1] 2071
[root@fedora23-1 contrib]# nmcli c up forti
VPN connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/30)
[root@fedora23-1 contrib]# nmcli c down forti
Connection 'forti' successfully deactivated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/30)
[root@fedora23-1 contrib]# >/var/log/audit/audit.log
[root@fedora23-1 contrib]# getenforce
Enforcing
[root@fedora23-1 contrib]# nmcli c up forti
VPN connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/32)
[root@fedora23-1 contrib]# ps -efZ |grep openfortivpn_t
system_u:system_r:openfortivpn_t:s0 root  2077     1  0 14:35 ?        00:00:00 /usr/libexec/nm-fortisslvpn-service
system_u:system_r:openfortivpn_t:s0 root  2221  2077  0 14:36 ?        00:00:00 /bin/openfortivpn -c /var/lib/NetworkManager-fortisslvpn/ebbb65c1-543c-4dc1-90d8-1a56de7cacf0.config --no-routes --no-dns localhost 10443 --ca-file /home/lkundrak/.cert/server.crt --user-cert /home/lkundrak/.cert/server.crt --user-key /home/lkundrak/.cert/server.key --trusted-cert a209d08fccdf1618f7d3161593ce10bab51272fc779b4c08a0425ffa48a8d2a3 --plugin /usr/lib64/pppd/2.4.7/nm-fortisslvpn-pppd-plugin.so
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 root 2288 2056  0 14:36 pts/0 00:00:00 grep --color=auto openfortivpn_t
[root@fedora23-1 contrib]# ps -efZ |grep pppd_t
system_u:system_r:pppd_t:s0     root      2481  2478  0 14:38 pts/1    00:00:00 /usr/sbin/pppd 38400 noipdefault noaccomp noauth default-asyncmap nopcomp receive-all nodefaultroute :1.1.1.1 nodetach lcp-max-configure 40 usepeerdns mru 1354 plugin /usr/lib64/pppd/2.4.7/nm-fortisslvpn-pppd-plugin.so
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 root 2558 2056  0 14:39 pts/0 00:00:00 grep --color=auto pppd_t
[root@fedora23-1 contrib]# nmcli c down forti
Connection 'forti' successfully deactivated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/32)
[root@fedora23-1 contrib]# cat /var/log/audit/audit.log
type=SERVICE_STOP msg=audit(1444394158.068:201): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
type=SERVICE_START msg=audit(1444394165.137:202): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
type=SERVICE_STOP msg=audit(1444394175.068:203): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
type=SERVICE_START msg=audit(1444394184.297:204): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
type=SERVICE_STOP msg=audit(1444394195.070:205): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[root@fedora23-1 contrib]#
</pre>

**Comment by lkundrak** [comment]
Eek, GitHub seems to have swallowed all the review and history.

Nevertheless; the v1 commit is b7049e5875273808256e2e53081ef31b95f4f0dc and I believe I've addressed everything there.

Works for me with no denials. (same tests as above)

**Comment by doverride** [comment]
Looks okay to me (except for a style error)

**Comment by lkundrak** [comment]
@doverride please point to the error in an inline comment. As for the style I was attempting to merely copy what's in place already but I could've easily done something wrong.

**Comment by lkundrak** [comment]
I tried to address the style violations. Maybe there's some left; I'm having trouble following the guide -- is there a tool to do the style checking?

Also, sorting things alphabetically makes it a bit difficult to place comments. By a quick glance at other modules it seems there really are not many useful comments. Is commenting actively discouraged?

**Comment by doverride** [comment]
I do not believe that there is a tool for style checking. policy modules are pretty generic. 

Good observation. oten people have a hard time adding the right comments. they often comment stuff that doesnt need to be be commented, and neglect to add meaningful comments

Same with git commit messages. Just have a look at some of them.

I enourage comments but only if they're useful. otherwise I remove them. As for others, I can't speak for them.

**Comment by mgrepl** [comment]
Yes, correct commit messages are really important. I believe we did a progress with them.

**Comment by mgrepl** [comment]
I made some tyle changes - 7fa40. Really good job. Thank you.

**Pull request merged**
