### PR TITLE
Allow subscription manager run kpatch

### PR DESCRIPTION
**Pull request by zpytela**

### CODE REVIEW

**Comment by zpytela** [comment]
The scratchbuild seems to allow the permissions as requested.

**Comment by WOnder93** [comment]
The first commit adds an empty `CHECKING` file. I guess that's not intentional?

Also, I think it would make more sense to do a transition here (there is one even from unconfined_t). Even if it doesn't make much difference in this case, it would be more consistent.

**Comment by zpytela** [comment]
A transition was the first thing I considered, but in this case kpatch is used only to gather information for subscription manager.
Thanks for spotting the empty file.

**Comment by WOnder93** [comment]
The CHECKING file is still there :)

I thought a bit more about the exec vs transition and I conclude that it's probably OK like this.

**Comment by zpytela** [comment]
So trying again, hope the file is not immortal.

**Review by WOnder93 — APPROVED** [review]

**Comment by zpytela** [comment]
Having double-checked no file creeped in in the meantime, merging.

**Pull request merged**
