### PR TITLE
Rawhide contrib

### PR DESCRIPTION
**Pull request by ssekidde**

### CODE REVIEW

**Comment by ssekidde** [comment]
98c311a has been corrected with 53e4346

**Comment by ssekidde** [comment]
Agreed. Changes reverted in 0602f60

**Comment by wrabcak** [comment]
Simon, 
We need to clean up this pull request, and merge your fixes.

**Comment by ssekidde** [comment]
Lukas should I close pull request #16 and start afresh?

**Comment by wrabcak** [comment]
Yes

**Pull request closed without merging**
