### PR TITLE
Allow nsd_crond_t write nsd_var_run_t & connectto nsd_t

### PR DESCRIPTION
**Pull request by 5umm3r15**
Allow nsd_crond_t connect to nsd_t unix_stream_socket Allow nsd_crond_t manage nsd_var_run_t sock_files

Resolves: rhbz#2209973

### CODE REVIEW

**Comment by zpytela** [comment]
If managing the sock files is not really needed, stream_socket_pattern seems to match semantically better.

**Comment by 5umm3r15** [comment]
@zpytela can you please look at it now?

**Comment by zpytela** [comment]
I actually meant stream_connect_pattern, see https://github.com/fedora-selinux/selinux-policy/blob/rawhide/policy/modules/contrib/samba.te#L309

**Comment by 5umm3r15** [comment]
Fixed, thank you

**Comment by zpytela** [comment]
LGTM now

**Pull request merged**
