### PR TITLE
Drop cockpit module and stop ignoring standalone interface files

### PR DESCRIPTION
**Pull request by vmojzis**

### CODE REVIEW

**Comment by vmojzis** [comment]
This is an alternative to https://github.com/fedora-selinux/selinux-policy/pull/853

**Comment by vmojzis** [comment]
Again, the build-rpm fail is expected since cockpit needs to be removed from modules-targeted-contrib.conf (but setting it to "OFF" is not necessary with this approach).

**Comment by vmojzis** [comment]
Rebased

**Comment by marusak** [comment]
Any update on this?

**Comment by zpytela** [comment]
> Any update on this?

Now it's time to move it forward.

**Comment by vmojzis** [comment]
Rebased.

**Comment by vmojzis** [comment]
rebased

**Comment by zpytela** [comment]
Merged, thank you for the effort.

**Pull request merged**
