### PR TITLE
Sync the policy_capabilities file with refpolicy and enable genfs_seclabel_symlinks

### PR DESCRIPTION
**Pull request by WOnder93**
See commit messages for more details.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
I suspect that the /proc/net symlink label could potentially cause slight disruption. It probably changed from proc_t to proc_net_t with this patch

**Comment by WOnder93** [comment]
Indeed it is now `proc_net_t`, but `kernel_read_network_state()` already defines the necessary `lnk_file` permissions and there is also `kernel_read_network_state_symlinks()` used with a couple domains, so this shouldn't cause much, if any, disruption.

**Comment by ghost** [comment]
Ondrej Mosnáček ***@***.***> writes:

> Indeed it is now proc_net_t, but kernel_read_network_state() already defines the necessary lnk_file
> permissions and there is also kernel_read_network_state_symlinks() used with a couple domains, so this
> shouldn't cause much, if any, disruption.


Alright, nice.

Strange though that the interfaces facilitated reading proc_net_t
symlinks as I would imagine that without this policy capability there
would never be any, since proc_t is not a seclabel fs.

>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 
gpg --locate-keys ***@***.***
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
Dominick Grift

**Comment by zpytela** [comment]
Merging, thank you.

**Pull request merged**
