### PR TITLE
Remove obsolete modules

### PR DESCRIPTION
**Pull request by WOnder93**
This PR removes modules that fulfil these two conditions:
* They are not built/shipped in Fedora selinux-policy packages.
* They are not present in the current refpolicy sources.

Note that corresponding interface calls and optional policy blocks are also removed here (otherwise the policy wouldn't even build).

### CODE REVIEW

**Comment by WOnder93** [comment]
(Rebased to pick up the container-selinux CI patch.)

**Comment by zpytela** [comment]
Thank you Ondrej, I am sorry it took me some time to get through it so rebasing is now needed, would you mind doing it?

For some of the modules there are additional reasons for removing, like package no longer maintained or

**Comment by WOnder93** [comment]
> Thank you Ondrej, I am sorry it took me some time to get through it so rebasing is now needed, would you mind doing it?

Yes, sure.

> For some of the modules there are additional reasons for removing, like package no longer maintained or

Fogot to finish the sentence? :)

**Comment by zpytela** [comment]
Looks I haven't received notification about the rebase. Merging now, thank you.

**Pull request merged**
