### PR TITLE
Allow virt_qemu_ga_t create .ssh dir with correct label

### PR DESCRIPTION
**Pull request by 5umm3r15**
Create .ssh directory in the user home directory with an correct label.

Add capabilities: chown dac_override dac_read_search fsetid fowner

Resolves: rhbz#2181402

### CODE REVIEW

**Comment by zpytela** [comment]
Do I understand correctly the newly added permissions match the purpose of the `virt_qemu_ga_manage_ssh` boolean or is the scenario any different?

**Comment by 5umm3r15** [comment]
Yes, this is correct. 
.ssh directory was created with wrong label user_home_dir_t and should be fixed with  ssh_filetrans_home_content.

Also based on [Milos comment](https://bugzilla.redhat.com/show_bug.cgi?id=2181402#c9) capabilities were required.

**Comment by zpytela** [comment]
So both the groups should be inside a tunable_policy block?

**Comment by 5umm3r15** [comment]
I had problem with inserting filetrans rule into tunable policy. There was error

**Comment by zpytela** [comment]
I see. Would it make sense then (semantically) put the additional allow rules to either tunable or optional block which these rules belong to?

**Comment by 5umm3r15** [comment]
Can you please check it now?

**Comment by zpytela** [comment]
Better, can you also move the allow rules to the optional block?

**Comment by 5umm3r15** [comment]
This way?
```
optional_policy(`
    allow virt_qemu_ga_t self:capability { chown dac_override dac_read_search fowner fsetid };
    ssh_filetrans_home_content(virt_qemu_ga_t)
        tunable_policy(`virt_qemu_ga_manage_ssh',`
                ssh_manage_home_files(virt_qemu_ga_t)
        ')
')
```

**Comment by 5umm3r15** [comment]
This way? Or to the tunable?

```
optional_policy(`
    allow virt_qemu_ga_t self:capability { chown dac_override dac_read_search fowner fsetid };
    ssh_filetrans_home_content(virt_qemu_ga_t)
        tunable_policy(`virt_qemu_ga_manage_ssh',`
                ssh_manage_home_files(virt_qemu_ga_t)
        ')
')
```

**Comment by zpytela** [comment]
In which case are they needed? I believe it rather should be inside the tunable block, but I may not read the bz properly.

**Comment by 5umm3r15** [comment]
I wasn't able to test it properly, so fixes are based on the comments

**Comment by zpytela** [comment]
OK, merging.

**Pull request merged**
