### PR TITLE
"Targetd" policy upgrade.

### PR DESCRIPTION
**Pull request by vmojzis**

### CODE REVIEW

**Comment by mgrepl** [comment]
files_create_lock_dirs(targetd_t)

why is this needed? Does it create own lock?

**Comment by mgrepl** [comment]
Also I would use

storage_raw_read_fixed_disk()

**Comment by vmojzis** [comment]
In case /var/lock/lvm directory does not exist (targetd creates lock files there).

**Comment by vmojzis** [comment]
Targetd does not need fixed_disk_raw_read which is described as extremely dangerous as it can bypass the SELinux protections for filesystem objects.

**Comment by mgrepl** [comment]
Ok but in this case there should be called a new interface with filename transition rule for /var/lock/lvm.

Something like

lvm_filetrans_named_lock()

and should have

files_lock_filetrans($1, lvm_lock_t, dir, "lvm")

**Comment by mgrepl** [comment]
Well but you want to allow to access a disk by 

storage_read_fixed_disk()

which is the same.

**Comment by wrabcak** [comment]
In some cases, we forced to allow some "extremely dangerous" actions. It's storage daemon and due to usability it's needs this rule. The challenge of writing policies for SELinux is find balance between security/usability. You could allow it, but after that, you must be careful with domtrans to this domain.

**Pull request closed without merging**
