### PR TITLE
Allow tcpdump sniffing offloaded (RDMA) traffic

### PR DESCRIPTION
**Pull request by zpytela**
Allow netutils_t create and use netlink_rdma_socket

### CODE REVIEW

**Comment by wrabcak** [comment]
Hi @zpytela , 
Policy cannot be compiled with this change: https://travis-ci.org/github/fedora-selinux/selinux-policy/builds/686506639#L2017

**Comment by zpytela** [comment]
I see. Preparing a scratchbuild now.

**Comment by zpytela** [comment]
Ran the policy tcpdump test with the scratchbuild containing this change, the denial agreed to fix is gone.

**Comment by wrabcak** [comment]
LGTM.

**Pull request merged**
